# This is a basic workflow to help you get started with Actions

name: test-upload

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      ssh:
        required: false
        default: 'true'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo 开始执行

      # Runs a set of commands using the runners shell
      - name: touch xz file
        run: |
          mkdir -p output/images
          cd output/images
          echo "FIRMWARE=$PWD" >> $GITHUB_ENV
          dd if=/dev/zero of=./file.img.xz bs=1M count=20
      
      - name: install transfer
        run: |
          curl -fsSL git.io/file-transfer | sh
          ./tranfer wet ${FIRMWARE}/*.xz

      - name: SSH connection to Actions
        uses: P3TERX/ssh2actions@v1.0.0
        if: ${{ failure() }}
        
      - name: upload to artifact
        uses: actions/upload-artifact@main
        with:
          name: test
          path: ${FIRMWARE}/*.xz


